# Generated by Django 3.2.6 on 2021-08-27 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLost',
            fields=[
                ('ItemID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('found', models.BooleanField(default=False)),
                ('location', models.TextField(max_length=100)),
                ('lost_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='', upload_to='findme/images')),
                ('found_location', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
